export const insurances = [
  "Mutua Madrileña (Adeslas)",
  "Sanitas",
  "Asisa",
  "DKV",
  "Mapfre",
  "IMQ – Igualatorio Médico Quirúrgico",
  "Asistencia Sanitaria Colegial",
  "AXA",
  "Fiatc",
  "Catalana Occidente",
  "Caser",
  "Generali",
  "Allianz",
  "Asefa",
  "Aegon",
  "Cigna",
  "Antares",
  "Divina Pastora",
  "Zurich",
  "Santa Lucía",
  "Qualitas Auto",
  "Ima Ibérica",
  "Almudena",
  "La Fe",
  "GES",
  "MGS",
  "HNA",
  "Previsora General",
  "ASSSA",
  "Mutua General de Cataluña",
  "Meridiano",
  "Metlife",
  "Clinicum Salut",
  "Asistencia Sanitaria",
  "Other"
];
